repos:
    -   repo: https://github.com/dotnet/format
        rev: "v8.0.453106"
        hooks:
            -   id: dotnet-format
                name: dotnet-format
                language: system
                entry: dotnet format -v:diag --include
                types_or: ["c#", "vb"]