#https://www.keycloak.org/server/db
version: "3"

services:
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:25.0
        ports:
            - "80:8080"
        volumes:
            - ./providers:/opt/keycloak/providers
        environment:
            PROXY_ADDRESS_FORWARDING: "true"
            KC_PROXY_HEADERS: xforwarded

            KC_HOSTNAME_ADMIN_URL:
            KC_HOSTNAME_URL:

            KEYCLOAK_ADMIN:
            KEYCLOAK_ADMIN_PASSWORD:

            KC_DB: mssql
            KC_DB_USERNAME:
            KC_DB_PASSWORD:
            KC_DB_URL_DATABASE:
            KC_DB_URL_HOST:
            KC_DB_URL_PROPERTIES: ";trustServerCertificate=true;encrypt=false;persistSecurityInfo=false;sendStringParametersAsUnicode=false;"
        command:
            - start-dev
        restart: unless-stopped