services:
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:25.0
        ports:
            - "7842:8080"
        volumes:
            - ./providers:/opt/keycloak/providers
        environment:
            PROXY_ADDRESS_FORWARDING: "true"
            KC_PROXY_HEADERS: xforwarded

            KC_HOSTNAME_ADMIN_URL: "http://:7842"
            KC_HOSTNAME_URL: "http://:7842"

            KEYCLOAK_ADMIN: KcAdmin
            KEYCLOAK_ADMIN_PASSWORD: Vbk7Taayus5zkK

            KC_DB: mssql
            KC_DB_USERNAME: DB_SUPPORT
            KC_DB_PASSWORD: Y5qkg%fD7BhQ
            KC_DB_URL: "jdbc:sqlserver://Palych;instanceName=Luton;databaseName=WEIGHT_KC;trustServerCertificate=true;encrypt=false;persistSecurityInfo=false;sendStringParametersAsUnicode=false;"
        command:
            - start-dev
        restart: unless-stopped
