name: Branch Main

on:
  push:
    branches:
      - main
    paths:
      - '**.csproj'
      - '**.razor'
      - '**.cs'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
  
      - name: Setup Nuget Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Install dependencies
        run: nuget restore WeightService2022.sln

      - name: Build app for ReleaseVS Any CPU
        run: msbuild WeightService2022.sln -t:rebuild -verbosity:quiet -property:Configuration=ReleaseVS -property:Platform="x64"
      
      - name: Tests for DevelopVS Any CPU
        run: |
            dotnet test Tests/Ws.Labels.Tests/Ws.Labels.Tests.csproj --no-restore --verbosity quiet -property:Configuration=ReleaseVS -property:Platform="x64"
            dotnet test Tests/Ws.Shared.Tests/Ws.Shared.Tests.csproj --no-restore --verbosity quiet -property:Configuration=ReleaseVS -property:Platform="x64"