name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration ReleaseVS --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity quiet --configuration ReleaseVS