name: Build and Test

on:
  push:
    branches:
      - main
      - bagger
#    paths:
#      - '**.cs'
#      - '**.csproj'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Nuget Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        run: nuget restore WeightService2022.sln

      - name: Build
        run: msbuild WeightService2022.sln

      - name: Tests
        run: dotnet test WeightService2022.sln --no-restore --verbosity normal