name: PVS-Studio build analysis
on: workflow_dispatch
jobs:
  build-analyze:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install tools
        run: |
          Invoke-WebRequest -Uri "https://cdn.pvs-studio.com/PVS-Studio_setup.exe" -OutFile "PVS-Studio_setup.exe"
          PVS-Studio_setup.exe
          PVS-Studio_Cmd.exe credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}
      - name: Build app for DevelopVS x64
        run: msbuild WeightService2022.sln -t:rebuild -verbosity:quiet -property:Configuration=DevelopVS -property:Platform=x64
      - name: Analyze
        run: |
          pvs-studio-analyzer analyze -f build/compile_commands.json -j
      - name: Convert report
        run: |
          plog-converter -t sarif -o pvs-report.sarif PVS-Studio.log
      - name: Publish report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio
